Misc changes.
Signed-off-by: Hal Gentz <zegentzy@protonmail.com>

diff --git a/gabs-build b/gabs-build
--- a/gabs-build
+++ b/gabs-build
@@ -4,12 +4,7 @@
 local SCRIPTS_DIR="${0:A:h}"
 [[ ! -d "${SCRIPTS_DIR}" ]] && exit 1
 
-local BUILTIN_PACKAGES_DIR=
-
 source "${SCRIPTS_DIR}/gabs-build-common" || exit $?
-source "${SCRIPTS_DIR}/gabs-build-config" || exit $?
-
-[[ ! -d "${BUILTIN_PACKAGES_DIR}" ]] && exit 1
 
 sudo_loop
 
@@ -27,133 +22,83 @@ local CHROOT_NAME=
 local LOOP_DEVICE_SIZE=50G
 local UNMOUNT_LOOP_DEVICE=true
 local EPHEMERAL_DIR=
+local BUILD_CONFIG_SCRIPT="${SCRIPTS_DIR}/gabs-build-config"
 
 while [[ $# -gt 0 ]]; do
-	case "$1" in
+	case "${1}" in
 		-r)
             if [[ "${SHOULD_RESUME}" != "false" ]]; then
-                echo -r conflicts with either other -r or -rp
+                >&2 echo -r conflicts with either other -r or -rp
                 exit 1
             fi
             SHOULD_RESUME=true
 		;;
 		-rp)
             if [[ "${SHOULD_RESUME}" != "false" ]]; then
-                echo -rp conflicts with either other -rp or -r
+                >&2 echo -rp conflicts with either other -rp or -r
                 exit 1
             fi
             SHOULD_RESUME=true
-            RESUME_PKG="$2"
+            RESUME_PKG="${2}"
 			shift
 		;;
         -ra) SHOULD_RESUME_AFTER=true;;
-		-p) PACKAGES+=("$2"); shift;;
-		-e) EXCLUDED_PACKAGES+=("$2"); shift;;
-		-fp) FIRST_PARAMS+=("$2"); shift;;
-		-ep) EVERY_PARAMS+=("$2"); shift;;
+		-p) PACKAGES+=("${2}"); shift;;
+		-e) EXCLUDED_PACKAGES+=("${2}"); shift;;
+		-fp) FIRST_PARAMS+=("${2}"); shift;;
+		-ep) EVERY_PARAMS+=("${2}"); shift;;
 		-o) ONE_ONLY=true;;
-		-rs)
-            if [[ "${RESUME_DIR}" != "" ]]; then
-                echo Resume backup dir already passed.
-                exit 1
-            fi
-
-            RESUME_DIR="$2"
-			shift
-		;;
-		-bk)
-            if [[ "${BACKUP_DIR}" != "" ]]; then
-                echo Do backup dir already passed.
-                exit 1
-            fi
-
-            BACKUP_DIR="$2"
-			shift
-		;;
-		-cn)
-            if [[ "${CHROOT_NAME}" != "" ]]; then
-                echo Chroot name already passed.
-                exit 1
-            fi
-
-            CHROOT_NAME="$2"
-			shift
-		;;
-        -lds) LOOP_DEVICE_SIZE="$2"; shift;;
+		-rs) RESUME_DIR="${2}"; shift;;
+		-bk) BACKUP_DIR="${2}"; shift;;
+		-cn) CHROOT_NAME="${2}"; shift;;
+        -lds) LOOP_DEVICE_SIZE="${2}"; shift;;
         -kld) UNMOUNT_LOOP_DEVICE=false;;
-        -ed) EPHEMERAL_DIR="$2"; shift;;
+        -ed) EPHEMERAL_DIR="${2}"; shift;;
+        -bcs) BUILD_CONFIG_SCRIPT="${2}"; shift;;
 
         --help)
-            echo "Please refer to the README."
+            >&2 echo "Please refer to the README."
             exit
         ;;
 		*) # unknown option
-			printf "Unkown option \`$1\`\n"
+			>&2 echo "Unkown option \"${1}\""
             exit 1
 		;;
 	esac
 	shift
 done
 
-error_blank_param EPHEMERAL_DIR
+BUILTIN_PACKAGES_DIR=
+source "${BUILD_CONFIG_SCRIPT}" || exit $?
+[[ ! -d "${BUILTIN_PACKAGES_DIR}" ]] && exit 1
+
+error_blank_param -d EPHEMERAL_DIR
 
 if [[ "${#EVERY_PARAMS[@]}" == "0" ]]; then
     EVERY_PARAMS=("-w")
-    change_fallback_param "EVERY_PARAMS" "${EVERY_PARAMS[@]}"
+    print_fallback_param "EVERY_PARAMS" "${EVERY_PARAMS[@]}"
 fi
 
 if [[ "${CHROOT_NAME}" == "" ]]; then
     CHROOT_NAME="chroot"
-    change_fallback_param "CHROOT_NAME" "${CHROOT_NAME}"
+    print_fallback_param "CHROOT_NAME" "${CHROOT_NAME}"
 fi
 
 if [[ "${SHOULD_RESUME}" == "true" && "${RESUME_PKG}" == "" ]]; then
     RESUME_PKG="$(cat "${EPHEMERAL_DIR}/last_pkg.${CHROOT_NAME}")"
-    change_fallback_param "RESUME_PKG" "${RESUME_PKG}"
+    print_fallback_param "RESUME_PKG" "${RESUME_PKG}"
 fi
 
-if [[ "${#PACKAGES[@]}" == "0" ]]; then
-    PACKAGES=(
-        "${BUILTIN_PACKAGES_DIR}/xorgproto-git-gentz"
-
-        "${BUILTIN_PACKAGES_DIR}/lib32-tk-gentz"
-        "${BUILTIN_PACKAGES_DIR}/lib32-mpdecimal-gentz"
-        "${BUILTIN_PACKAGES_DIR}/python2-gentz"
-        "${BUILTIN_PACKAGES_DIR}/python-gentz"
-
-        "${BUILTIN_PACKAGES_DIR}/libx11-git-gentz"
-
-        "${BUILTIN_PACKAGES_DIR}/lib32-libedit-gentz"
-        "${BUILTIN_PACKAGES_DIR}/llvm-git-gentz"
-
-        "${BUILTIN_PACKAGES_DIR}/openmpi-git-gentz"
-        "${BUILTIN_PACKAGES_DIR}/valgrind-git-gentz"
-
-        "${BUILTIN_PACKAGES_DIR}/lib32-libomxil-bellagio-gentz"
-        "${BUILTIN_PACKAGES_DIR}/libdrm-git-gentz"
-        "${BUILTIN_PACKAGES_DIR}/mesa-git-gentz"
-
-        "${BUILTIN_PACKAGES_DIR}/xorg-server-git-gentz"
-        "${BUILTIN_PACKAGES_DIR}/xf86-video-amdgpu-git-gentz"
-        "${BUILTIN_PACKAGES_DIR}/xf86-video-ati-git-gentz"
-        "${BUILTIN_PACKAGES_DIR}/xf86-video-fbdev-git-gentz"
-        "${BUILTIN_PACKAGES_DIR}/xf86-video-vesa-git-gentz"
-
-        "${BUILTIN_PACKAGES_DIR}/wine-staging-git-gentz"
-        "${BUILTIN_PACKAGES_DIR}/winetricks-git"
-    )
-
-    change_fallback_param "PACKAGES" "${PACKAGES[@]}"
-fi
+populate_builtins
 
 for PKG_DIR in ${PACKAGES}; do
     if [[ ! -d "${PKG_DIR}" ]]; then
-        echo "Package \"${PKG_DIR}\" is missing"
+        >&2 echo "Package \"${PKG_DIR}\" is missing"
         exit 1
     fi
 done
 
-mkdir -p "${EPHEMERAL_DIR}/custom"
+mkdir -p "${EPHEMERAL_DIR}/custom.${CHROOT_NAME}"
 
 # If line starts with BUILDENV and this option is "sign" add a "!".
 awk '{
@@ -175,7 +120,7 @@ awk '{
         }
         printf "\n"
     } else print
-}' /etc/makepkg.conf > "${EPHEMERAL_DIR}/custom/makepkg.conf"
+}' /etc/makepkg.conf > "${EPHEMERAL_DIR}/custom.${CHROOT_NAME}/makepkg.conf"
 
 local USE_DISTCC
 local USE_CCACHE
@@ -187,15 +132,10 @@ local CHROOT_MOUNT="${EPHEMERAL_DIR}/chroots/${CHROOT_NAME}"
 local CHROOT_FILE="${EPHEMERAL_DIR}/chroots/${CHROOT_NAME}.img"
 local PKGBUILD_CLONE_DIR="${EPHEMERAL_DIR}/pkgbuilds.${CHROOT_NAME}"
 
-# Unmount old loopdevices that where kept due to bad cleanup
-lsblk -o NAME,MOUNTPOINT -J -n \
-    | grep "${CHROOT_MOUNT}" \
-    | xargs -I% bash -xc '
-        LOOPDEVICE_NAME="$(echo "%" | cut -d":" -f2 | cut -d"," -f1)"
-        MOUNT_DIR="$(echo "%" | cut -d":" -f3 | cut -d"}" -f1)"
-        sudo umount "${MOUNT_DIR}"
-        sudo losetup -d "/dev/${LOOPDEVICE_NAME}"
-    '
+"${SCRIPTS_DIR}/gabs-build-chroot" \
+    -cm "${CHROOT_MOUNT}" \
+    -cf "${CHROOT_FILE}" \
+    -c
 
 local REMAKE_CHROOT=false
 [[ "${SHOULD_RESUME}" == "false" || ! -f "${CHROOT_FILE}" ]] \
@@ -219,8 +159,15 @@ if [[ "${REMAKE_CHROOT}" == "true" ]]; then
         "${EPHEMERAL_DIR}/pkgs.old.${CHROOT_NAME}"
 fi
 
-local LOOP_DEVICE="$(sudo losetup -f)"
-setup_loopdevice || exit $?
+local BUILD_CHROOT_PARAMS=()
+[[ "${REMAKE_CHROOT}" == true ]] && BUILD_CHROOT_PARAMS+="-rm"
+
+local LOOP_DEVICE="$("${SCRIPTS_DIR}/gabs-build-chroot" \
+    -cm "${CHROOT_MOUNT}" \
+    -cf "${CHROOT_FILE}" \
+    -lds "${LOOP_DEVICE_SIZE}" \
+    "${BUILD_CHROOT_PARAMS[@]}" \
+    -s || exit $?)"
 
 if [[ "${REMAKE_CHROOT}" == "true" ]]; then
     sudo mkdir -p "${CHROOT_DIR}"
@@ -233,7 +180,7 @@ if [[ "${REMAKE_CHROOT}" == "true" ]]; then
 
     sudo /usr/bin/mkarchroot \
         -C /etc/pacman.conf \
-        -M "${EPHEMERAL_DIR}/custom/makepkg.conf" \
+        -M "${EPHEMERAL_DIR}/custom.${CHROOT_NAME}/makepkg.conf" \
         -c /var/cache/pacman/pkg \
         "${CHROOT_DIR}/root" \
         "${INSTALL_PACKAGES[@]}" || exit $?
@@ -246,7 +193,7 @@ if [[ "${REMAKE_CHROOT}" == "true" ]]; then
         nspawn "${CHROOT_DIR}/root" /bin/bash -xc "yes | pacman -U /pkgs/*" || exit $?
     fi
 else
-    clone_file {"${EPHEMERAL_DIR}/custom",/etc}/makepkg.conf root:root 644
+    clone_file {"${EPHEMERAL_DIR}/custom.${CHROOT_NAME}",/etc}/makepkg.conf root:root 644
 
     for CHROOT_DIR2 in "${CHROOT_DIR}"/*; do
         [[ ! -d "${CHROOT_DIR2}" ]] && continue
@@ -274,8 +221,8 @@ fi
 
 for PKG_DIR in ${PACKAGES}; do
     if [[ "${SHOULD_RESUME}" != "false" ]]; then
-        if [[ "${PKG_DIR}" != "${RESUME_PKG}" ]]; then
-            echo "Skipping ${PKG_DIR}"
+        if [[ "${PKG_DIR}" != "$(eval "echo \"${RESUME_PKG}\"")" ]]; then
+            >&2 echo "Skipping ${PKG_DIR}"
             continue
         fi
         SHOULD_RESUME=false
@@ -285,15 +232,16 @@ for PKG_DIR in ${PACKAGES}; do
     fi
 
     if array_contains_element ${PKG_DIR} ${EXCLUDED_PACKAGES[@]} ; then
-        echo "Excluding ${PKG_DIR}"
+        >&2 echo "Excluding ${PKG_DIR}"
         continue
     fi
 
-    echo "Doing ${PKG_DIR}"
+    >&2 echo "Doing ${PKG_DIR}"
 
-    echo "${PKG_DIR}" > "${EPHEMERAL_DIR}/last_pkg.${CHROOT_NAME}"
+    >&2 echo "${PKG_DIR}" > "${EPHEMERAL_DIR}/last_pkg.${CHROOT_NAME}"
 
     local PARAMS=(${EVERY_PARAMS[@]})
+    local PKGNAME="$(basename "${PKG_DIR}").$(md5sum <(echo "${PKG_DIR}") | cut -d" " -f1)"
 
     if [[ "${#FIRST_PARAMS[@]}" != "0" ]]; then
         PARAMS=("${FIRST_PARAMS[@]}")
@@ -301,10 +249,10 @@ for PKG_DIR in ${PACKAGES}; do
     fi
 
     array_contains_element "-rs" ${PARAMS[@]} \
-        && echo "Did not insert -rs as already present" \
+        && >&2 echo "Did not insert -rs as already present" \
         || {
             [[ "${RESUME_DIR}" != "" ]] \
-                && PARAMS+=("-rs" "${RESUME_DIR}/$(basename "${PKG_DIR}")")
+                && PARAMS+=("-rs" "${RESUME_DIR}/$PKGNAME")
         }
 
     if array_contains_element "-rs" ${PARAMS[@]} ; then
@@ -315,10 +263,10 @@ for PKG_DIR in ${PACKAGES}; do
     fi
 
     array_contains_element "-bk" ${PARAMS[@]} \
-        && echo "Did not insert -bk as already present" \
+        && >&2 echo "Did not insert -bk as already present" \
         || {
             [[ "${BACKUP_DIR}" != "" ]] \
-                && PARAMS+=("-bk" "${BACKUP_DIR}/$(basename "${PKG_DIR}")")
+                && PARAMS+=("-bk" "${BACKUP_DIR}/$PKGNAME")
         }
 
     local BUILD_SCRIPT="${PKG_DIR}/gabs-build"
@@ -326,28 +274,31 @@ for PKG_DIR in ${PACKAGES}; do
         BUILD_SCRIPT="${SCRIPTS_DIR}/gabs-build-handler"
     fi
 
-    local PKGNAME="$(basename "${PKG_DIR}.$(md5sum <(echo "${PKG_DIR}") | cut -d" " -f1)")"
-
     mkdir -p "${PKGBUILD_CLONE_DIR}/${PKGNAME}"
     sudo rsync -chavPASWX --stats --inplace  --compress-level=0 \
         "${PKG_DIR}/" "${PKGBUILD_CLONE_DIR}/${PKGNAME}" || exit $?
 
     pushd "${PKGBUILD_CLONE_DIR}/${PKGNAME}"
-    echo "Delegating \"${PKG_DIR}\" @ \"${PKGBUILD_CLONE_DIR}/${PKGNAME}\" to \"${BUILD_SCRIPT}\""
+    >&2 echo "Delegating \"${PKG_DIR}\" @ \"${PKGBUILD_CLONE_DIR}/${PKGNAME}\" to \"${BUILD_SCRIPT}\""
     "${BUILD_SCRIPT}" "${PARAMS[@]}" \
         -c "${CHROOT_DIR}" \
         -cn "${CHROOT_NAME}" \
         -pn "${PKGNAME}" \
         -ed "${EPHEMERAL_DIR}" || {
         local ERROR=$?
-        echo "Failed to build ${PKG_DIR}"
+        >&2 echo "Failed to build ${PKG_DIR}"
         UNMOUNT_LOOP_DEVICE=false
         exit ${ERROR}
     }
-    echo "Done ${PKG_DIR}"
+    >&2 echo "Done ${PKG_DIR}"
     popd
 
     if [[ "${ONE_ONLY}" == "true" ]]; then
         exit
     fi
 done
+
+if [[ "${SHOULD_RESUME}" != "false" ]]; then
+    >&2 echo "Could not find package to resume at."
+    exit 1
+fi
diff --git a/gabs-build-common b/gabs-build-common
--- a/gabs-build-common
+++ b/gabs-build-common
@@ -4,8 +4,8 @@
 # Array names cannot start with RFA_
 remove_from_array() {
     RFA_RETURN=()
-    local RFA_ARRAY=$1
-    local RFA_TO_REMOVE=$2
+    local RFA_ARRAY=${1}
+    local RFA_TO_REMOVE=${2}
     for mem in "${(P)${RFA_ARRAY}[@]}"; do
         for remove in "${(P)${RFA_TO_REMOVE}[@]}"; do
             local KEEP=true
@@ -21,7 +21,7 @@ remove_from_array() {
 }
 
 array_contains_element () {
-    local e match="$1"
+    local e match="${1}"
     shift
     for e; do [[ "${e}" == "${match}" ]] && return 0; done
     return 1
@@ -41,13 +41,22 @@ sudo_loop() {
     done &
 }
 
-change_fallback_param() {
-    echo "Falling back to using \"${1}\" of \"${@:2}\"."
+print_fallback_param() {
+    >&2 echo "Falling back to using \"${1}\" of \"${@:2}\"."
 }
 
 error_blank_param() {
     if [[ "${(P)1}" == "" ]]; then
-        echo "\"$1\" was never passed."
+        >&2 echo "\"${1}\" was never passed."
+        exit 1
+    fi
+}
+
+error_blank_nondir_param() {
+    error_blank_param "${2}"
+
+    if [[ ("${1}" == "-f" && ! -f "${(P)2}") || ("${1}" == "-d" && ! -d "${(P)2}") ]]; then
+        >&2 echo "\"${2}\"'s directory \"${(P)2}\" does not exist."
         exit 1
     fi
 }
@@ -60,25 +69,26 @@ if_buildenv_uses() {
                 split(a[i], b, \")\");
                 for (j in b) if (j == 1) {
                     split(b[j], c, \" \")
-                    for(k in c) if(c[k] == tolower(\"$1\") || c[k] == tolower(\"!$1\"))
+                    for(k in c) if(c[k] == tolower(\"${1}\") || c[k] == tolower(\"!${1}\"))
                         printf c[k]
                 }
             }
         }
-    }" "${EPHEMERAL_DIR}/custom/makepkg.conf")" == "$(echo "$1" | awk '{ printf tolower($0) }')" ]]; then
-        eval USE_$1=true
+    }" "${EPHEMERAL_DIR}/custom.${CHROOT_NAME}/makepkg.conf")"
+        == "$(echo "${1}" | awk '{ printf tolower($0) }')" ]]; then
+        eval USE_${1}=true
     else
-        eval USE_$1=false
+        eval USE_${1}=false
     fi
 }
 
 clone_file() {
     for CHROOT_DIR2 in "${CHROOT_DIR}"/*; do
         [[ ! -d "${CHROOT_DIR2}" ]] && continue
-        sudo cp "$1" "${CHROOT_DIR2}$2"
+        sudo cp "${1}" "${CHROOT_DIR2}${2}"
 
-        sudo chown $3 "${CHROOT_DIR2}$2"
-        sudo chmod $4 "${CHROOT_DIR2}$2"
+        sudo chown ${3} "${CHROOT_DIR2}${2}"
+        sudo chmod ${4} "${CHROOT_DIR2}${2}"
     done
 }
 
@@ -95,6 +105,16 @@ cleanup_loopdevice3() {
         until sudo umount "${CHROOT_MOUNT}"; do sleep 2; done
         until sudo losetup -d "${LOOP_DEVICE}"; do sleep 2; done
     fi
+}
+
+# Unmount old loopdevices that where kept due to bad cleanup
+cleanup_loopdevice() {
+    losetup -j "${CHROOT_FILE}" \
+        | cut -d":" -f1 \
+        | xargs -I% bash -xc '
+            sudo umount "%"
+            sudo losetup -d "%"
+        '
 }
 
 # We use a loop device cause sometimes the partitions have nosuid on them,
